### PR TITLE
Revert "Setup simple USB search and remove iOS / macOS support"

### LINKED ISSUE #1: Please add iOS and Mac support back
I noticed we removed iOS and Mac Support, please add this back, this is mission-critical. I'm trying to keep the food on my employee's tables here.

### PR DESCRIPTION
**Pull request by tidusjar**
This reverts commit 42e66b9cb69cbdd2f4ecc4c85a5756feef3ed18d.

Fixes #1, #2 and #4

### CODE REVIEW

**Review by sophia-ma — APPROVED** [review]

**Comment by sophia-ma** [comment]
Good job ⭐️

**Comment by tidusjar** [comment]
TY

**Comment by bendotpw** [comment]
Approved ✅

**Comment by AmyJeanes** [comment]
Buy me a Mac and I might consider re-adding support

**Comment by sophia-ma** [comment]
This is not nice behaviour...

**Pull request closed without merging**
